const swaggerUi = require ('swagger-ui-express');
const swaggerJsDoc = require ('swagger-jsdoc');
	
const options = {
    "swagger": "2.0",
    swaggerDefinition: {

        info: {
            title: 'API Multas',
            version: '1.0.0',
            description: 'Test Express API with autogenerated swagger doc',    
        },
        basePath: '/',
        tags:[
            {
               name:'Multas',
               description:"API for multas"
            }
        ],
        schemes: [
            'http',
            'https'
        ],

        paths: {
            '/api/v1/multas': {
               post: {
                  tags: ['Multas'],
                  description: "Crear una nueva multa",
                  parameters: [
                    {
                      name :"Fine Parameters",
                      in: "body",
                      description: "Fine to add to the database",
                      required: true,
                    }
                  ],
                  responses: {
                    200: {
                      description: "create response",
                    }
                  }
               },
               get: {
                tags: ['Multas'],
                description: "Consultar las multas existentes",
                responses: {
                  200: {
                    description: "create response",
                  }
                }
              },
              delete: {
                tags: ['Multas'],
                description: "Eliminar todas las multas",
                responses: {
                  200: {
                    description: "create response",
                  }
                }
              }
            },

            '/api/v1/multas/:{dni}': { 
                get: {
                    tags: ['Multas'],
                    summary: 'Obtener multa por DNI',
                    parameters: [
                        {
                          dni : 'dni',
                          in: "path",
                          description: "El dni de la multa a recuperar. Use 918289B para pruebas",
                          required: true,
                        }
                      ],
                      responses: {
                        200: {
                          description: "Operacion correcta"
                        },
                        400: {
                          description: "DNI inválido"
                        },
                        404: {
                          description: "Multa no encontrada"
                        }
                      }
                },
                delete: {
                  tags: ['Multas'],
                  summary: 'Eliminar multas por dni',
                  parameters: [
                      {
                        dni : 'dni',
                        in: "path",
                        description: "El id de la multa a eliminar.",
                        required: true,
                      }
                    ],
                    responses: {
                      200: {
                        description: "Operacion correcta"
                      },
                      400: {
                        description: "DNI inválido"
                      },
                      404: {
                        description: "Multa no encontrada"
                      }
                    }
                 },
            },
            '/api/v1/multas/editar/:{dni}': {
                put: {
                    tags: ['Multas'],
                    summary: 'Actualizar multa por DNI',
                    parameters: [
                        {
                          dni : 'dni',
                          name :"Fine Parameters",
                          in: "path",
                          description: "El dni de la multa a actualizar. Use 918289B para pruebas",
                          required: true,
                        }
                    ],
                      responses: {
                        200: {
                          description: "Operacion correcta"
                        },
                        400: {
                          description: "DNI inválido"
                        },
                        404: {
                          description: "Multa no encontrada"
                        }
                      }
                }
            },
            
      
        },
    },
    apis: ['server.js'],
};

const specs = swaggerJsDoc(options);

module.exports = (app) =>{ 
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
}
