const swaggerUi = require ('swagger-ui-express');
const swaggerJsDoc = require ('swagger-jsdoc');

const options = {
    // "swagger": "2.0",
    "openapi": "3.0.0",
    swaggerDefinition: {

        info: {
            title: 'API Multas',
            version: '1.0.0',
            description: 'Test Express API with autogenerated swagger doc',    
        },
        basePath: '/',
        tags:[
            {
               name:'Multas',
               description:"API for multas"
            }
        ],
        schemes: [
            'http',
            'https'
        ],
        components: [
          {
            securityDefinitions:{
              APIKeyHeader: {
                "type": "apiKey",
                "in": "header",  
                "name": "apikey"  
              },
            },
          },
        ],

        security: {
            "APIKeyHeader": []
        },

        paths: {
            '/api/v1/multas': {
               post: {
                  tags: ['Multas'],
                  description: "Crear una nueva multa",
                  parameters: [
                    {
                      name :"Fine Parameters",
                      in: "body",
                      description: "Fine to add to the database",
                      required: true,
                    }
                  ],

                  responses: {
                    200: {
                      description: "create response",
                    }
                  }
               },
               get: {
                tags: ['Multas'],
                description: "Consultar las multas existentes",
                responses: {
                  200: {
                    description: "create response",
                  },
                
                },
                security:[{
                  APIKeyHeader: [],
              }
              ],
              }

            },

            '/api/v1/multas/{dni}': { 
                get: {
                    tags: ['Multas'],
                    summary: 'Obtener multa por DNI',
                    parameters: [
                        {
                          name : 'dni',
                          in: "path",
                          description: "El dni de la multa a recuperar. Use 918289B para pruebas",
                          required: true,
                        }
                      ],
                      responses: {
                        200: {
                          description: "Operacion correcta"
                        },
                        400: {
                          description: "DNI inválido"
                        },
                        404: {
                          description: "Multa no encontrada"
                        }
                      }
                },
            },
            '/api/v1/multas/editar/{dni}': {
                put: {
                    tags: ['Multas'],
                    summary: 'Actualizar multa por DNI',
                    parameters: [
                        {
                          name: 'dni',
                          in: "path",
                          description: "El dni de la multa a actualizar. Use 11111111A para pruebas",
                          required: true,
                          type: "string"
                        }
                      ],
                      responses: {
                        200: {
                          description: "Operacion correcta"
                        },
                        400: {
                          description: "DNI inválido"
                        },
                        404: {
                          description: "Multa no encontrada"
                        }
                      }
                }
            }
        },
    },
    apis: ['server.js'],
};

const specs = swaggerJsDoc(options);

module.exports = (app) =>{ 
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
}